/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsersListResponse } from '../../models/users-list-response';

export interface GetActiveUsers$Params {
}

export function getActiveUsers(http: HttpClient, rootUrl: string, params?: GetActiveUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<UsersListResponse>> {
  const rb = new RequestBuilder(rootUrl, getActiveUsers.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsersListResponse>;
    })
  );
}

getActiveUsers.PATH = '/users/active';
