/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DownloadPhoto$Jpeg$Params {

/**
 * Photo ID
 */
  photoId: number;
}

export function downloadPhoto$Jpeg(http: HttpClient, rootUrl: string, params: DownloadPhoto$Jpeg$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, downloadPhoto$Jpeg.PATH, 'get');
  if (params) {
    rb.path('photoId', params.photoId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'image/jpeg', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

downloadPhoto$Jpeg.PATH = '/photos/{photoId}/download';
