/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhotoResponse } from '../../models/photo-response';

export interface GetPhotoById$Params {

/**
 * Photo ID
 */
  photoId: number;
}

export function getPhotoById(http: HttpClient, rootUrl: string, params: GetPhotoById$Params, context?: HttpContext): Observable<StrictHttpResponse<PhotoResponse>> {
  const rb = new RequestBuilder(rootUrl, getPhotoById.PATH, 'get');
  if (params) {
    rb.path('photoId', params.photoId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhotoResponse>;
    })
  );
}

getPhotoById.PATH = '/photos/{photoId}';
