/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhotosListResponse } from '../../models/photos-list-response';

export interface GetPhotosByTripId$Params {

/**
 * Trip ID
 */
  id: number;
}

export function getPhotosByTripId(http: HttpClient, rootUrl: string, params: GetPhotosByTripId$Params, context?: HttpContext): Observable<StrictHttpResponse<PhotosListResponse>> {
  const rb = new RequestBuilder(rootUrl, getPhotosByTripId.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhotosListResponse>;
    })
  );
}

getPhotosByTripId.PATH = '/photos/trips/{id}/photos';
