/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhotoResponse } from '../../models/photo-response';

export interface SetMainPhoto$Params {

/**
 * Trip ID
 */
  id: number;

/**
 * Photo ID
 */
  photoId: number;
}

export function setMainPhoto(http: HttpClient, rootUrl: string, params: SetMainPhoto$Params, context?: HttpContext): Observable<StrictHttpResponse<PhotoResponse>> {
  const rb = new RequestBuilder(rootUrl, setMainPhoto.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('photoId', params.photoId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhotoResponse>;
    })
  );
}

setMainPhoto.PATH = '/photos/trips/{id}/photos/{photoId}/main';
