/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhotoResponse } from '../../models/photo-response';
import { UpdateCaption } from '../../models/update-caption';

export interface UpdatePhotoCaption$Params {

/**
 * Photo ID
 */
  photoId: number;
      body: UpdateCaption
}

export function updatePhotoCaption(http: HttpClient, rootUrl: string, params: UpdatePhotoCaption$Params, context?: HttpContext): Observable<StrictHttpResponse<PhotoResponse>> {
  const rb = new RequestBuilder(rootUrl, updatePhotoCaption.PATH, 'patch');
  if (params) {
    rb.path('photoId', params.photoId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhotoResponse>;
    })
  );
}

updatePhotoCaption.PATH = '/photos/{photoId}/caption';
