/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhotoUploadResponse } from '../../models/photo-upload-response';

export interface UploadPhotos$Params {

/**
 * Trip ID
 */
  id: number;
      body: {

/**
 * Photo files to upload (max 10)
 */
'photos'?: Array<Blob>;
}
}

export function uploadPhotos(http: HttpClient, rootUrl: string, params: UploadPhotos$Params, context?: HttpContext): Observable<StrictHttpResponse<PhotoUploadResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadPhotos.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhotoUploadResponse>;
    })
  );
}

uploadPhotos.PATH = '/photos/trips/{id}/photos';
