/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SearchLocations$Params {

/**
 * Search query string
 */
  q: string;

/**
 * Maximum number of results
 */
  limit?: number;
}

export function searchLocations(http: HttpClient, rootUrl: string, params: SearchLocations$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'success'?: boolean;
'data'?: Array<{

/**
 * External ID from geocoding service
 */
'externalId'?: string;

/**
 * Location name
 */
'name'?: string;

/**
 * Full display name
 */
'displayName'?: string;
'latitude'?: number;
'longitude'?: number;
'country'?: string;
'countryCode'?: string;
}>;
}>> {
  const rb = new RequestBuilder(rootUrl, searchLocations.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'success'?: boolean;
      'data'?: Array<{
      
      /**
       * External ID from geocoding service
       */
      'externalId'?: string;
      
      /**
       * Location name
       */
      'name'?: string;
      
      /**
       * Full display name
       */
      'displayName'?: string;
      'latitude'?: number;
      'longitude'?: number;
      'country'?: string;
      'countryCode'?: string;
      }>;
      }>;
    })
  );
}

searchLocations.PATH = '/locations/search';
