/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateSportEvent } from '../../models/create-sport-event';
import { SportEventResponse } from '../../models/sport-event-response';

export interface CreateSportEvent$Params {
      body: CreateSportEvent
}

export function createSportEvent(http: HttpClient, rootUrl: string, params: CreateSportEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<SportEventResponse>> {
  const rb = new RequestBuilder(rootUrl, createSportEvent.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SportEventResponse>;
    })
  );
}

createSportEvent.PATH = '/sport-events';
