/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SportEventResponse } from '../../models/sport-event-response';

export interface GetSportEventById$Params {

/**
 * Sport event ID
 */
  id: number;
}

export function getSportEventById(http: HttpClient, rootUrl: string, params: GetSportEventById$Params, context?: HttpContext): Observable<StrictHttpResponse<SportEventResponse>> {
  const rb = new RequestBuilder(rootUrl, getSportEventById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SportEventResponse>;
    })
  );
}

getSportEventById.PATH = '/sport-events/{id}';
