/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SportEventsListResponse } from '../../models/sport-events-list-response';

export interface GetAllSportEvents$Params {
}

export function getAllSportEvents(http: HttpClient, rootUrl: string, params?: GetAllSportEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<SportEventsListResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllSportEvents.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SportEventsListResponse>;
    })
  );
}

getAllSportEvents.PATH = '/sport-events';
