/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SportEventResponse } from '../../models/sport-event-response';
import { UpdateSportEvent } from '../../models/update-sport-event';

export interface UpdateSportEvent$Params {

/**
 * Sport event ID
 */
  id: number;
      body: UpdateSportEvent
}

export function updateSportEvent(http: HttpClient, rootUrl: string, params: UpdateSportEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<SportEventResponse>> {
  const rb = new RequestBuilder(rootUrl, updateSportEvent.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SportEventResponse>;
    })
  );
}

updateSportEvent.PATH = '/sport-events/{id}';
