/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateWeatherType } from '../../models/create-weather-type';
import { WeatherTypeResponse } from '../../models/weather-type-response';

export interface CreateWeatherType$Params {
      body: CreateWeatherType
}

export function createWeatherType(http: HttpClient, rootUrl: string, params: CreateWeatherType$Params, context?: HttpContext): Observable<StrictHttpResponse<WeatherTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, createWeatherType.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeatherTypeResponse>;
    })
  );
}

createWeatherType.PATH = '/weather-types';
