/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTransportationType } from '../../models/create-transportation-type';
import { TransportationTypeResponse } from '../../models/transportation-type-response';

export interface CreateTransportationType$Params {
      body: CreateTransportationType
}

export function createTransportationType(http: HttpClient, rootUrl: string, params: CreateTransportationType$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportationTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, createTransportationType.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransportationTypeResponse>;
    })
  );
}

createTransportationType.PATH = '/transportation-types';
