/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WeatherTypeResponse } from '../../models/weather-type-response';

export interface GetWeatherTypeById$Params {

/**
 * Weather type ID (WMO code)
 */
  id: number;
}

export function getWeatherTypeById(http: HttpClient, rootUrl: string, params: GetWeatherTypeById$Params, context?: HttpContext): Observable<StrictHttpResponse<WeatherTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, getWeatherTypeById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeatherTypeResponse>;
    })
  );
}

getWeatherTypeById.PATH = '/weather-types/{id}';
