/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccommodationTypesListResponse } from '../../models/accommodation-types-list-response';

export interface GetAllAccommodationTypes$Params {
}

export function getAllAccommodationTypes(http: HttpClient, rootUrl: string, params?: GetAllAccommodationTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<AccommodationTypesListResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllAccommodationTypes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccommodationTypesListResponse>;
    })
  );
}

getAllAccommodationTypes.PATH = '/accommodation-types';
