/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransportationTypeResponse } from '../../models/transportation-type-response';

export interface GetTransportationTypeById$Params {

/**
 * Transportation type ID
 */
  id: number;
}

export function getTransportationTypeById(http: HttpClient, rootUrl: string, params: GetTransportationTypeById$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportationTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, getTransportationTypeById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransportationTypeResponse>;
    })
  );
}

getTransportationTypeById.PATH = '/transportation-types/{id}';
