/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WeatherTypesListResponse } from '../../models/weather-types-list-response';

export interface GetAllWeatherTypes$Params {
}

export function getAllWeatherTypes(http: HttpClient, rootUrl: string, params?: GetAllWeatherTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<WeatherTypesListResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllWeatherTypes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeatherTypesListResponse>;
    })
  );
}

getAllWeatherTypes.PATH = '/weather-types';
