/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransportationTypesListResponse } from '../../models/transportation-types-list-response';

export interface GetAllTransportationTypes$Params {
}

export function getAllTransportationTypes(http: HttpClient, rootUrl: string, params?: GetAllTransportationTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportationTypesListResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllTransportationTypes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransportationTypesListResponse>;
    })
  );
}

getAllTransportationTypes.PATH = '/transportation-types';
