/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateWeatherType } from '../../models/update-weather-type';
import { WeatherTypeResponse } from '../../models/weather-type-response';

export interface UpdateWeatherType$Params {

/**
 * Weather type ID
 */
  id: number;
      body: UpdateWeatherType
}

export function updateWeatherType(http: HttpClient, rootUrl: string, params: UpdateWeatherType$Params, context?: HttpContext): Observable<StrictHttpResponse<WeatherTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, updateWeatherType.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeatherTypeResponse>;
    })
  );
}

updateWeatherType.PATH = '/weather-types/{id}';
