/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccommodationTypeResponse } from '../../models/accommodation-type-response';
import { UpdateAccommodationType } from '../../models/update-accommodation-type';

export interface UpdateAccommodationType$Params {

/**
 * Accommodation type ID
 */
  id: number;
      body: UpdateAccommodationType
}

export function updateAccommodationType(http: HttpClient, rootUrl: string, params: UpdateAccommodationType$Params, context?: HttpContext): Observable<StrictHttpResponse<AccommodationTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, updateAccommodationType.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccommodationTypeResponse>;
    })
  );
}

updateAccommodationType.PATH = '/accommodation-types/{id}';
