/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WeatherTypeResponse } from '../../models/weather-type-response';

export interface UploadWeatherTypeIcon$Params {

/**
 * Weather type ID
 */
  id: number;
      body: {
'icon'?: Blob;
}
}

export function uploadWeatherTypeIcon(http: HttpClient, rootUrl: string, params: UploadWeatherTypeIcon$Params, context?: HttpContext): Observable<StrictHttpResponse<WeatherTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadWeatherTypeIcon.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeatherTypeResponse>;
    })
  );
}

uploadWeatherTypeIcon.PATH = '/weather-types/{id}/icon';
