/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateDiaryType } from '../../models/create-diary-type';
import { DiaryTypeResponse } from '../../models/diary-type-response';

export interface CreateDiaryType$Params {
      body: CreateDiaryType
}

export function createDiaryType(http: HttpClient, rootUrl: string, params: CreateDiaryType$Params, context?: HttpContext): Observable<StrictHttpResponse<DiaryTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, createDiaryType.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DiaryTypeResponse>;
    })
  );
}

createDiaryType.PATH = '/diaries/types';
