/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DiaryTypeResponse } from '../../models/diary-type-response';

export interface GetDiaryTypeById$Params {

/**
 * Diary type ID
 */
  id: number;
}

export function getDiaryTypeById(http: HttpClient, rootUrl: string, params: GetDiaryTypeById$Params, context?: HttpContext): Observable<StrictHttpResponse<DiaryTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, getDiaryTypeById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DiaryTypeResponse>;
    })
  );
}

getDiaryTypeById.PATH = '/diaries/types/{id}';
