/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DiariesListResponse } from '../../models/diaries-list-response';

export interface GetDiariesByTripId$Params {

/**
 * Trip ID
 */
  tripId: number;
}

export function getDiariesByTripId(http: HttpClient, rootUrl: string, params: GetDiariesByTripId$Params, context?: HttpContext): Observable<StrictHttpResponse<DiariesListResponse>> {
  const rb = new RequestBuilder(rootUrl, getDiariesByTripId.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DiariesListResponse>;
    })
  );
}

getDiariesByTripId.PATH = '/diaries/trip/{tripId}';
