/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DiaryResponse } from '../../models/diary-response';
import { UpdateDiary } from '../../models/update-diary';

export interface UpdateDiary$Params {

/**
 * Diary ID
 */
  id: number;
      body: UpdateDiary
}

export function updateDiary(http: HttpClient, rootUrl: string, params: UpdateDiary$Params, context?: HttpContext): Observable<StrictHttpResponse<DiaryResponse>> {
  const rb = new RequestBuilder(rootUrl, updateDiary.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DiaryResponse>;
    })
  );
}

updateDiary.PATH = '/diaries/{id}';
