/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhotoUploadResponse } from '../../models/photo-upload-response';

export interface AddPhotosToTrip$Params {

/**
 * Trip ID
 */
  tripId: number;
      body: {

/**
 * Photos to add (max 100)
 */
'photos'?: Array<Blob>;
}
}

export function addPhotosToTrip(http: HttpClient, rootUrl: string, params: AddPhotosToTrip$Params, context?: HttpContext): Observable<StrictHttpResponse<PhotoUploadResponse>> {
  const rb = new RequestBuilder(rootUrl, addPhotosToTrip.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhotoUploadResponse>;
    })
  );
}

addPhotosToTrip.PATH = '/trips/{tripId}/add-photos';
