/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddCountryRequest } from '../../models/add-country-request';
import { TripResponse } from '../../models/trip-response';

export interface AddCountryToTrip$Params {

/**
 * Trip ID
 */
  id: number;
      body: AddCountryRequest
}

export function addCountryToTrip(http: HttpClient, rootUrl: string, params: AddCountryToTrip$Params, context?: HttpContext): Observable<StrictHttpResponse<TripResponse>> {
  const rb = new RequestBuilder(rootUrl, addCountryToTrip.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripResponse>;
    })
  );
}

addCountryToTrip.PATH = '/trips/{id}/countries';
