/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTrip } from '../../models/create-trip';
import { TripResponse } from '../../models/trip-response';

export interface CreateTrip$Params {
      body: CreateTrip
}

export function createTrip(http: HttpClient, rootUrl: string, params: CreateTrip$Params, context?: HttpContext): Observable<StrictHttpResponse<TripResponse>> {
  const rb = new RequestBuilder(rootUrl, createTrip.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripResponse>;
    })
  );
}

createTrip.PATH = '/trips';
