/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripResponse } from '../../models/trip-response';

export interface CreateTripFromPhotos$Params {
      body: {

/**
 * Photos to create trip from (max 100)
 */
'photos'?: Array<Blob>;

/**
 * User ID for the trip
 */
'userId'?: number;

/**
 * Trip name (optional, will be generated if not provided)
 */
'name'?: string;
}
}

export function createTripFromPhotos(http: HttpClient, rootUrl: string, params: CreateTripFromPhotos$Params, context?: HttpContext): Observable<StrictHttpResponse<TripResponse>> {
  const rb = new RequestBuilder(rootUrl, createTripFromPhotos.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripResponse>;
    })
  );
}

createTripFromPhotos.PATH = '/trips/create-from-photos';
