/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripsListResponse } from '../../models/trips-list-response';

export interface GetTripsByDateRange$Params {

/**
 * Start date (ISO 8601)
 */
  startDate: string;

/**
 * End date (ISO 8601)
 */
  endDate: string;
}

export function getTripsByDateRange(http: HttpClient, rootUrl: string, params: GetTripsByDateRange$Params, context?: HttpContext): Observable<StrictHttpResponse<TripsListResponse>> {
  const rb = new RequestBuilder(rootUrl, getTripsByDateRange.PATH, 'get');
  if (params) {
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripsListResponse>;
    })
  );
}

getTripsByDateRange.PATH = '/trips/date-range';
