/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripsListResponse } from '../../models/trips-list-response';

export interface GetTripsByUserId$Params {

/**
 * User ID
 */
  userId: number;
}

export function getTripsByUserId(http: HttpClient, rootUrl: string, params: GetTripsByUserId$Params, context?: HttpContext): Observable<StrictHttpResponse<TripsListResponse>> {
  const rb = new RequestBuilder(rootUrl, getTripsByUserId.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripsListResponse>;
    })
  );
}

getTripsByUserId.PATH = '/trips/user/{userId}';
