/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Location } from '../../models/location';

export interface GetLocationsByTripId$Params {

/**
 * Trip ID
 */
  id: number;
}

export function getLocationsByTripId(http: HttpClient, rootUrl: string, params: GetLocationsByTripId$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'success'?: boolean;
'data'?: Array<Location>;
}>> {
  const rb = new RequestBuilder(rootUrl, getLocationsByTripId.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'success'?: boolean;
      'data'?: Array<Location>;
      }>;
    })
  );
}

getLocationsByTripId.PATH = '/trips/{id}/locations';
