/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripsListResponse } from '../../models/trips-list-response';

export interface GetTripsByCountry$Params {

/**
 * Country ID
 */
  countryId: number;
}

export function getTripsByCountry(http: HttpClient, rootUrl: string, params: GetTripsByCountry$Params, context?: HttpContext): Observable<StrictHttpResponse<TripsListResponse>> {
  const rb = new RequestBuilder(rootUrl, getTripsByCountry.PATH, 'get');
  if (params) {
    rb.path('countryId', params.countryId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripsListResponse>;
    })
  );
}

getTripsByCountry.PATH = '/trips/country/{countryId}';
