/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripsListResponse } from '../../models/trips-list-response';

export interface GetTripsByRating$Params {

/**
 * Minimum rating (0-10)
 */
  minRating?: number;

/**
 * Maximum rating (0-10)
 */
  maxRating?: number;
}

export function getTripsByRating(http: HttpClient, rootUrl: string, params?: GetTripsByRating$Params, context?: HttpContext): Observable<StrictHttpResponse<TripsListResponse>> {
  const rb = new RequestBuilder(rootUrl, getTripsByRating.PATH, 'get');
  if (params) {
    rb.query('minRating', params.minRating, {});
    rb.query('maxRating', params.maxRating, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripsListResponse>;
    })
  );
}

getTripsByRating.PATH = '/trips/rating';
