/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripResponse } from '../../models/trip-response';

export interface RemoveLocationFromTrip$Params {

/**
 * Trip ID
 */
  id: number;

/**
 * Location ID
 */
  locationId: number;
}

export function removeLocationFromTrip(http: HttpClient, rootUrl: string, params: RemoveLocationFromTrip$Params, context?: HttpContext): Observable<StrictHttpResponse<TripResponse>> {
  const rb = new RequestBuilder(rootUrl, removeLocationFromTrip.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('locationId', params.locationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripResponse>;
    })
  );
}

removeLocationFromTrip.PATH = '/trips/{id}/locations/{locationId}';
