/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ValidatePhotosResponse } from '../../models/validate-photos-response';

export interface ValidatePhotos$Params {
      body: {

/**
 * Photos to validate (max 100)
 */
'photos'?: Array<Blob>;
}
}

export function validatePhotos(http: HttpClient, rootUrl: string, params: ValidatePhotos$Params, context?: HttpContext): Observable<StrictHttpResponse<ValidatePhotosResponse>> {
  const rb = new RequestBuilder(rootUrl, validatePhotos.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ValidatePhotosResponse>;
    })
  );
}

validatePhotos.PATH = '/trips/validate-photos';
