/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CountryResponse } from '../../models/country-response';
import { UpdateCountry } from '../../models/update-country';

export interface UpdateCountry$Params {

/**
 * Country ID
 */
  id: number;
      body: UpdateCountry
}

export function updateCountry(http: HttpClient, rootUrl: string, params: UpdateCountry$Params, context?: HttpContext): Observable<StrictHttpResponse<CountryResponse>> {
  const rb = new RequestBuilder(rootUrl, updateCountry.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CountryResponse>;
    })
  );
}

updateCountry.PATH = '/countries/{id}';
