/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CountryResponse } from '../../models/country-response';

export interface UploadCountryFlag$Params {

/**
 * Country ID
 */
  id: number;
      body: {

/**
 * Flag image file (PNG, JPG, SVG)
 */
'flag'?: Blob;
}
}

export function uploadCountryFlag(http: HttpClient, rootUrl: string, params: UploadCountryFlag$Params, context?: HttpContext): Observable<StrictHttpResponse<CountryResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadCountryFlag.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CountryResponse>;
    })
  );
}

uploadCountryFlag.PATH = '/countries/{id}/flag';
