/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetYearsSummary$Params {

/**
 * The user ID to filter trips
 */
  userId: number;
}

export function getYearsSummary(http: HttpClient, rootUrl: string, params: GetYearsSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'success'?: boolean;
'message'?: string;
'data'?: Array<{
'year'?: number;
'tripCount'?: number;
'countries'?: Array<{
'id'?: number;
'nameEnglish'?: string;
'nameSpanish'?: string;
'isoCode'?: string;
'flagPath'?: string | null;
}>;
}>;
}>> {
  const rb = new RequestBuilder(rootUrl, getYearsSummary.PATH, 'get');
  if (params) {
    rb.query('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'success'?: boolean;
      'message'?: string;
      'data'?: Array<{
      'year'?: number;
      'tripCount'?: number;
      'countries'?: Array<{
      'id'?: number;
      'nameEnglish'?: string;
      'nameSpanish'?: string;
      'isoCode'?: string;
      'flagPath'?: string | null;
      }>;
      }>;
      }>;
    })
  );
}

getYearsSummary.PATH = '/calendar';
