/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Trip } from '../../models/trip';

export interface GetTripsByMonth$Params {

/**
 * The year to query
 */
  year: number;

/**
 * The month to query (1-12)
 */
  month: number;

/**
 * The user ID to filter trips
 */
  userId: number;
}

export function getTripsByMonth(http: HttpClient, rootUrl: string, params: GetTripsByMonth$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'success'?: boolean;
'message'?: string;
'data'?: Array<Trip>;
}>> {
  const rb = new RequestBuilder(rootUrl, getTripsByMonth.PATH, 'get');
  if (params) {
    rb.path('year', params.year, {});
    rb.path('month', params.month, {});
    rb.query('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'success'?: boolean;
      'message'?: string;
      'data'?: Array<Trip>;
      }>;
    })
  );
}

getTripsByMonth.PATH = '/calendar/{year}/{month}';
