/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccommodationType } from '../models/accommodation-type';
export interface AccommodationTypeResponse {
  data?: AccommodationType;
  message?: string;
  success?: boolean;
}
