/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccommodationType } from '../models/accommodation-type';
export interface AccommodationTypesListResponse {
  data?: Array<AccommodationType>;
  message?: string;
  success?: boolean;
}
