/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
export type AccommodationType = BaseEntity & {

/**
 * Accommodation type name in Spanish
 */
'nameSpanish': string;

/**
 * Accommodation type name in English
 */
'nameEnglish': string;

/**
 * Icon filename
 */
'icon'?: string | null;

/**
 * Full URL to accommodation icon
 */
'iconURL'?: string | null;
};

