/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiResponseError {
  error?: {
'code'?: string;
'details'?: string;
};
  message?: string;
  success: boolean;
}
