/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BaseEntity {

  /**
   * Creation timestamp
   */
  createdAt?: string;

  /**
   * Unique identifier
   */
  id?: number;

  /**
   * Last update timestamp
   */
  updatedAt?: string;
}
