/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
export type Country = BaseEntity & {

/**
 * Country name in Spanish
 */
'nameSpanish': string;

/**
 * Country name in English
 */
'nameEnglish': string;

/**
 * ISO 3166-1 alpha-3 code
 */
'isoCode': string;

/**
 * Country center latitude
 */
'latitude': number;

/**
 * Country center longitude
 */
'longitude': number;

/**
 * Continent name
 */
'continent': string;

/**
 * Path to country flag image
 */
'flagPath'?: string | null;
};

