/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Country } from '../models/country';
export interface CountryResponse {
  data?: Country;
  message?: string;
  success?: boolean;
}
