/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Country } from '../models/country';
export interface CountriesListResponse {
  data?: Array<Country>;
  message?: string;
  success?: boolean;
}
