/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePoi {

  /**
   * POI latitude
   */
  latitude?: number;

  /**
   * Associated location ID
   */
  locationId?: number;

  /**
   * POI longitude
   */
  longitude?: number;

  /**
   * POI name in English
   */
  nameEnglish?: string;

  /**
   * POI name in Spanish
   */
  nameSpanish: string;

  /**
   * OpenStreetMap ID (optional)
   */
  osmId?: string;

  /**
   * POI type ID
   */
  poiTypeId: number;
}
