/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateLocation {

  /**
   * Continent name (optional)
   */
  continent?: string;

  /**
   * Country name
   */
  country: string;

  /**
   * Country ISO code (optional, for auto-linking)
   */
  countryIsoCode?: string;

  /**
   * Country latitude (optional)
   */
  countryLatitude?: number;

  /**
   * Country longitude (optional)
   */
  countryLongitude?: number;

  /**
   * External ID from geocoding service
   */
  externalId: string;

  /**
   * Location latitude
   */
  latitude: number;

  /**
   * Location longitude
   */
  longitude: number;

  /**
   * Location name
   */
  name: string;
}
