/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDiaryType {

  /**
   * Diary type description
   */
  description?: string;

  /**
   * Diary type name
   */
  name: string;
}
