/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCountry {

  /**
   * Continent name
   */
  continent: string;

  /**
   * ISO 3166-1 alpha-3 code
   */
  isoCode: string;

  /**
   * Country center latitude
   */
  latitude: number;

  /**
   * Country center longitude
   */
  longitude: number;

  /**
   * Country name in English
   */
  nameEnglish: string;

  /**
   * Country name in Spanish
   */
  nameSpanish: string;
}
