/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateWeatherType {

  /**
   * Weather description
   */
  description?: string;

  /**
   * Icon filename or emoji
   */
  icon?: string;

  /**
   * WMO weather code
   */
  id: number;

  /**
   * Weather type name in English
   */
  nameEnglish: string;

  /**
   * Weather type name in Spanish
   */
  nameSpanish: string;
}
