/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSportEvent {

  /**
   * Race bib number
   */
  bib?: string;

  /**
   * Whether the event was completed
   */
  completed: boolean;

  /**
   * Distance in kilometers
   */
  distance?: number;

  /**
   * Date of the event (ISO 8601)
   */
  eventDate: string;

  /**
   * Name of the event
   */
  eventName: string;

  /**
   * Associated sport ID
   */
  sportId: number;

  /**
   * Time spent (HH:MM:SS format)
   */
  timeSpent?: string;

  /**
   * Associated trip ID
   */
  tripId: number;
}
