/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTransportationType {

  /**
   * Icon filename
   */
  icon?: string;

  /**
   * Transportation type name in English
   */
  nameEnglish: string;

  /**
   * Transportation type name in Spanish
   */
  nameSpanish: string;
}
