/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSport {

  /**
   * Icon filename (optional)
   */
  icon?: string;

  /**
   * Sport name in English
   */
  nameEnglish: string;

  /**
   * Sport name in Spanish
   */
  nameSpanish: string;
}
