/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTrip {

  /**
   * Accommodation type ID
   */
  accommodationTypeId?: number;

  /**
   * Single country ID (legacy)
   */
  countryId?: number;

  /**
   * Array of country IDs to associate
   */
  countryIds?: Array<number>;

  /**
   * Trip description
   */
  description?: string;

  /**
   * Trip end date (ISO 8601)
   */
  endDate: string;

  /**
   * Main country ID
   */
  mainCountryId?: number;

  /**
   * Trip name
   */
  name: string;

  /**
   * Trip rating (0-10)
   */
  rating?: number;

  /**
   * Trip start date (ISO 8601)
   */
  startDate: string;

  /**
   * Transportation type ID
   */
  transportationTypeId?: number;

  /**
   * Owner user ID
   */
  userId: number;

  /**
   * Weather type ID
   */
  weatherTypeId?: number;
}
