/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDiary {

  /**
   * Date of the diary entry (ISO 8601)
   */
  day: string;

  /**
   * Diary entry content
   */
  description?: string;

  /**
   * Diary type ID
   */
  diaryTypeId?: number;

  /**
   * Array of location IDs to associate
   */
  locationIds?: Array<number>;

  /**
   * Array of photo IDs to associate
   */
  photoIds?: Array<number>;

  /**
   * Diary entry title
   */
  title: string;

  /**
   * Associated trip ID
   */
  tripId: number;

  /**
   * Weather type ID
   */
  weatherTypeId?: number;
}
