/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePoiType {

  /**
   * POI type name in English
   */
  nameEnglish: string;

  /**
   * POI type name in Spanish
   */
  nameSpanish: string;
}
