/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Diary } from '../models/diary';
export interface DiariesListResponse {
  data?: Array<Diary>;
  message?: string;
  success?: boolean;
}
