/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
import { Location } from '../models/location';
import { Photo } from '../models/photo';
export type Diary = BaseEntity & {

/**
 * Date of the diary entry
 */
'day': string;

/**
 * Diary entry title
 */
'title': string;

/**
 * Diary entry content
 */
'description'?: string | null;

/**
 * Associated trip ID
 */
'tripId': number;

/**
 * Diary type ID
 */
'diaryTypeId'?: number | null;

/**
 * Weather type ID for this day
 */
'weatherTypeId'?: number | null;

/**
 * Photos associated with this diary entry
 */
'photos'?: Array<Photo>;

/**
 * Locations visited on this day
 */
'locations'?: Array<Location>;
};

