/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
export type DiaryType = BaseEntity & {

/**
 * Diary type name
 */
'name': string;

/**
 * Diary type description
 */
'description'?: string | null;
};

