/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DiaryType } from '../models/diary-type';
export interface DiaryTypesListResponse {
  data?: Array<DiaryType>;
  message?: string;
  success?: boolean;
}
