/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Diary } from '../models/diary';
export interface DiaryResponse {
  data?: Diary;
  message?: string;
  success?: boolean;
}
