/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
import { Country } from '../models/country';
export type Location = BaseEntity & {

/**
 * External location ID (e.g., from geocoding service)
 */
'externalId'?: string | null;

/**
 * Location name
 */
'name': string;

/**
 * Location latitude
 */
'latitude': number;

/**
 * Location longitude
 */
'longitude': number;

/**
 * Associated country ID
 */
'countryId'?: number | null;
'country'?: Country;
};

