/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Location } from '../models/location';
export interface LocationResponse {
  data?: Location;
  message?: string;
  success?: boolean;
}
