/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Location } from '../models/location';
export interface LocationsListResponse {
  data?: Array<Location>;
  message?: string;
  success?: boolean;
}
