/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Login {

  /**
   * User email or alias
   */
  emailOrAlias: string;

  /**
   * User password
   */
  password: string;
}
