/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhotoWeather {

  /**
   * Weather description
   */
  description?: string | null;

  /**
   * Humidity percentage
   */
  humidity?: number | null;
  id?: number;
  photoId?: number;

  /**
   * Temperature at photo location
   */
  temperature?: number | null;
}
