/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Photo } from '../models/photo';
export interface PhotoResponse {
  data?: Photo;
  message?: string;
  success?: boolean;
}
