/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
import { PhotoWeather } from '../models/photo-weather';
export type Photo = BaseEntity & {

/**
 * Generated filename
 */
'filename': string;

/**
 * Original uploaded filename
 */
'originalName': string;

/**
 * File path on server
 */
'path': string;

/**
 * Photo caption/description
 */
'caption'?: string | null;

/**
 * Whether this is the main photo for the trip
 */
'isMain'?: boolean;

/**
 * Associated trip ID
 */
'tripId': number;

/**
 * GPS latitude from EXIF
 */
'latitude'?: number | null;

/**
 * GPS longitude from EXIF
 */
'longitude'?: number | null;

/**
 * Date photo was taken (local time)
 */
'dateTaken'?: string | null;

/**
 * Date photo was taken (UTC)
 */
'dateTakenUTC'?: string | null;

/**
 * Timezone where photo was taken
 */
'timezone'?: string | null;

/**
 * Camera model from EXIF
 */
'cameraModel'?: string | null;

/**
 * Camera make from EXIF
 */
'cameraMake'?: string | null;

/**
 * File MIME type
 */
'mimeType': string;

/**
 * File size in bytes
 */
'size': number;

/**
 * Additional EXIF metadata (JSON string)
 */
'metadata'?: string | null;
'photoWeather'?: PhotoWeather;
};

