/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Photo } from '../models/photo';
export interface PhotoUploadResponse {
  data?: {

/**
 * Number of photos uploaded
 */
'uploaded'?: number;
'photos'?: Array<Photo>;
};
  message?: string;
  success?: boolean;
}
