/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Photo } from '../models/photo';
export interface PhotosListResponse {
  data?: Array<Photo>;
  message?: string;
  success?: boolean;
}
