/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PoiType } from '../models/poi-type';
export interface PoiTypesListResponse {
  data?: Array<PoiType>;
  message?: string;
  success?: boolean;
}
