/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PoiType } from '../models/poi-type';
export interface PoiTypeResponse {
  data?: PoiType;
  message?: string;
  success?: boolean;
}
