/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
export type PoiType = BaseEntity & {

/**
 * POI type name in Spanish
 */
'nameSpanish': string;

/**
 * POI type name in English
 */
'nameEnglish': string;
};

