/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
export type Poi = BaseEntity & {

/**
 * POI name in Spanish
 */
'nameSpanish': string;

/**
 * POI name in English
 */
'nameEnglish'?: string;

/**
 * POI latitude
 */
'latitude'?: number;

/**
 * POI longitude
 */
'longitude'?: number;

/**
 * OpenStreetMap ID
 */
'osmId'?: string | null;
'poiType': {
'id'?: number;
'nameSpanish'?: string;
'nameEnglish'?: string;
};
'location'?: {
'id'?: number;
'name'?: string;
};
};

