/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Poi } from '../models/poi';
export interface PoisListResponse {
  data?: Array<Poi>;
  message?: string;
  success?: boolean;
}
