/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
export type Sport = BaseEntity & {

/**
 * Sport name in Spanish
 */
'nameSpanish': string;

/**
 * Sport name in English
 */
'nameEnglish': string;

/**
 * Icon filename
 */
'icon'?: string | null;

/**
 * Full URL to sport icon
 */
'iconUrl'?: string | null;
};

