/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
export type SportEvent = BaseEntity & {

/**
 * Date of the sport event
 */
'eventDate': string;

/**
 * Name of the event
 */
'eventName': string;

/**
 * Distance in kilometers
 */
'distance'?: number | null;

/**
 * Race bib number
 */
'bib'?: string | null;

/**
 * Time spent (duration format)
 */
'timeSpent'?: string | null;

/**
 * Whether the event was completed
 */
'completed': boolean;

/**
 * Associated trip ID
 */
'tripId': number;

/**
 * Associated sport ID
 */
'sportId': number;
};

