/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Sport } from '../models/sport';
export interface SportResponse {
  data?: Sport;
  message?: string;
  success?: boolean;
}
