/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SportEvent } from '../models/sport-event';
export interface SportEventResponse {
  data?: SportEvent;
  message?: string;
  success?: boolean;
}
