/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransportationType } from '../models/transportation-type';
export interface TransportationTypeResponse {
  data?: TransportationType;
  message?: string;
  success?: boolean;
}
