/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransportationType } from '../models/transportation-type';
export interface TransportationTypesListResponse {
  data?: Array<TransportationType>;
  message?: string;
  success?: boolean;
}
