/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Trip } from '../models/trip';
export interface TripResponse {
  data?: Trip;
  message?: string;
  success?: boolean;
}
