/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccommodationType } from '../models/accommodation-type';
import { BaseEntity } from '../models/base-entity';
import { Country } from '../models/country';
import { Location } from '../models/location';
import { Photo } from '../models/photo';
import { TransportationType } from '../models/transportation-type';
import { WeatherType } from '../models/weather-type';
export type Trip = BaseEntity & {

/**
 * Trip name
 */
'name': string;

/**
 * Trip description
 */
'description'?: string | null;

/**
 * Trip start date
 */
'startDate': string;

/**
 * Trip end date
 */
'endDate': string;

/**
 * Trip rating (0-10)
 */
'rating'?: number | null;

/**
 * Owner user ID
 */
'userId': number;
'mainPhoto'?: Photo;
'locations'?: Array<Location>;
'countries'?: Array<Country>;

/**
 * Main country ID
 */
'mainCountryId'?: number | null;
'mainCountry'?: Country;

/**
 * Weather type ID
 */
'weatherTypeId'?: number | null;
'weatherType'?: WeatherType;

/**
 * Accommodation type ID
 */
'accommodationTypeId'?: number | null;
'accommodationType'?: AccommodationType;

/**
 * Transportation type ID
 */
'transportationTypeId'?: number | null;
'transportationType'?: TransportationType;
};

