/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Trip } from '../models/trip';
export interface TripsListResponse {
  data?: Array<Trip>;
  message?: string;
  success?: boolean;
}
