/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCountry {
  continent?: string;
  latitude?: number;
  longitude?: number;
  nameEnglish?: string;
  nameSpanish?: string;
}
