/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateWeatherType {
  description?: string;
  icon?: string;
  nameEnglish?: string;
  nameSpanish?: string;
}
