/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUser {

  /**
   * Unique user alias
   */
  alias?: string;

  /**
   * Unique user email
   */
  email?: string;

  /**
   * User first name
   */
  firstName?: string;

  /**
   * User last name
   */
  lastName?: string;

  /**
   * New password (min 6 characters)
   */
  password?: string;
}
