/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateSportEvent {
  bib?: string;
  completed?: boolean;
  distance?: number;
  eventDate?: string;
  eventName?: string;
  sportId?: number;
  timeSpent?: string;
  tripId?: number;
}
