/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTrip {
  accommodationTypeId?: number | null;
  countryIds?: Array<number>;
  description?: string;
  endDate?: string;
  mainCountryId?: number;
  name?: string;
  rating?: number;
  startDate?: string;
  transportationTypeId?: number | null;
  weatherTypeId?: number | null;
}
