/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateDiary {
  day?: string;
  description?: string;
  diaryTypeId?: number;
  locationIds?: Array<number>;
  photoIds?: Array<number>;
  title?: string;
  tripId?: number;
  weatherTypeId?: number;
}
