/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePoi {
  latitude?: number;
  locationId?: number;
  longitude?: number;
  nameEnglish?: string;
  nameSpanish?: string;
  osmId?: string;
  poiTypeId?: number;
}
