/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseEntity } from '../models/base-entity';
export type User = BaseEntity & {

/**
 * Unique user alias
 */
'alias': string;

/**
 * Unique user email
 */
'email': string;

/**
 * User first name
 */
'firstName': string;

/**
 * User last name
 */
'lastName': string;

/**
 * Whether the user is active
 */
'active': boolean;

/**
 * Last access timestamp
 */
'lastAccessDate'?: string | null;
};

