/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface UsersListResponse {
  data?: Array<User>;
  message?: string;
  success?: boolean;
}
