/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ValidatePhotosResponse {
  data?: {

/**
 * Number of valid photos
 */
'validPhotos'?: number;

/**
 * Number of invalid photos
 */
'invalidPhotos'?: number;

/**
 * Suggested trip name based on photos
 */
'suggestedName'?: string;
'suggestedStartDate'?: string;
'suggestedEndDate'?: string;
'countries'?: Array<{
'id'?: number;
'name'?: string;
}>;
};
  message?: string;
  success?: boolean;
}
