/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WeatherType } from '../models/weather-type';
export interface WeatherTypesListResponse {
  data?: Array<WeatherType>;
  message?: string;
  success?: boolean;
}
