/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WeatherType } from '../models/weather-type';
export interface WeatherTypeResponse {
  data?: WeatherType;
  message?: string;
  success?: boolean;
}
