/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WeatherType {

  /**
   * Weather description
   */
  description?: string | null;

  /**
   * Icon filename or emoji
   */
  icon?: string | null;

  /**
   * Full URL to weather icon
   */
  iconURL?: string | null;

  /**
   * WMO weather code
   */
  id: number;

  /**
   * Weather type name in English
   */
  nameEnglish: string;

  /**
   * Weather type name in Spanish
   */
  nameSpanish: string;
}
