/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SportsListResponse } from '../../models/sports-list-response';

export interface GetAllSports$Params {
}

export function getAllSports(http: HttpClient, rootUrl: string, params?: GetAllSports$Params, context?: HttpContext): Observable<StrictHttpResponse<SportsListResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllSports.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SportsListResponse>;
    })
  );
}

getAllSports.PATH = '/sports';
