/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SportResponse } from '../../models/sport-response';

export interface GetSportById$Params {

/**
 * Sport ID
 */
  id: number;
}

export function getSportById(http: HttpClient, rootUrl: string, params: GetSportById$Params, context?: HttpContext): Observable<StrictHttpResponse<SportResponse>> {
  const rb = new RequestBuilder(rootUrl, getSportById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SportResponse>;
    })
  );
}

getSportById.PATH = '/sports/{id}';
