/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SportResponse } from '../../models/sport-response';
import { UpdateSport } from '../../models/update-sport';

export interface UpdateSport$Params {

/**
 * Sport ID
 */
  id: number;
      body: UpdateSport
}

export function updateSport(http: HttpClient, rootUrl: string, params: UpdateSport$Params, context?: HttpContext): Observable<StrictHttpResponse<SportResponse>> {
  const rb = new RequestBuilder(rootUrl, updateSport.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SportResponse>;
    })
  );
}

updateSport.PATH = '/sports/{id}';
