/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePoi } from '../../models/create-poi';
import { PoiResponse } from '../../models/poi-response';

export interface CreatePoi$Params {
      body: CreatePoi
}

export function createPoi(http: HttpClient, rootUrl: string, params: CreatePoi$Params, context?: HttpContext): Observable<StrictHttpResponse<PoiResponse>> {
  const rb = new RequestBuilder(rootUrl, createPoi.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PoiResponse>;
    })
  );
}

createPoi.PATH = '/pois';
