/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePoiType } from '../../models/create-poi-type';
import { PoiTypeResponse } from '../../models/poi-type-response';

export interface CreatePoiType$Params {
      body: CreatePoiType
}

export function createPoiType(http: HttpClient, rootUrl: string, params: CreatePoiType$Params, context?: HttpContext): Observable<StrictHttpResponse<PoiTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, createPoiType.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PoiTypeResponse>;
    })
  );
}

createPoiType.PATH = '/poi-types';
