/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeletePoiType$Params {

/**
 * POI type ID
 */
  id: number;
}

export function deletePoiType(http: HttpClient, rootUrl: string, params: DeletePoiType$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'success'?: boolean;
'message'?: string;
}>> {
  const rb = new RequestBuilder(rootUrl, deletePoiType.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'success'?: boolean;
      'message'?: string;
      }>;
    })
  );
}

deletePoiType.PATH = '/poi-types/{id}';
