/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PoiTypesListResponse } from '../../models/poi-types-list-response';

export interface GetAllPoiTypes$Params {
}

export function getAllPoiTypes(http: HttpClient, rootUrl: string, params?: GetAllPoiTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<PoiTypesListResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllPoiTypes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PoiTypesListResponse>;
    })
  );
}

getAllPoiTypes.PATH = '/poi-types';
