/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PoisListResponse } from '../../models/pois-list-response';

export interface GetPoisByPoiTypeId$Params {

/**
 * POI type ID
 */
  poiTypeId: number;
}

export function getPoisByPoiTypeId(http: HttpClient, rootUrl: string, params: GetPoisByPoiTypeId$Params, context?: HttpContext): Observable<StrictHttpResponse<PoisListResponse>> {
  const rb = new RequestBuilder(rootUrl, getPoisByPoiTypeId.PATH, 'get');
  if (params) {
    rb.path('poiTypeId', params.poiTypeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PoisListResponse>;
    })
  );
}

getPoisByPoiTypeId.PATH = '/pois/poi-type/{poiTypeId}';
