/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PoiTypeResponse } from '../../models/poi-type-response';

export interface GetPoiTypeById$Params {

/**
 * POI type ID
 */
  id: number;
}

export function getPoiTypeById(http: HttpClient, rootUrl: string, params: GetPoiTypeById$Params, context?: HttpContext): Observable<StrictHttpResponse<PoiTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, getPoiTypeById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PoiTypeResponse>;
    })
  );
}

getPoiTypeById.PATH = '/poi-types/{id}';
