/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PoiResponse } from '../../models/poi-response';

export interface GetPoiById$Params {

/**
 * POI ID
 */
  id: number;
}

export function getPoiById(http: HttpClient, rootUrl: string, params: GetPoiById$Params, context?: HttpContext): Observable<StrictHttpResponse<PoiResponse>> {
  const rb = new RequestBuilder(rootUrl, getPoiById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PoiResponse>;
    })
  );
}

getPoiById.PATH = '/pois/{id}';
