/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PoiTypeResponse } from '../../models/poi-type-response';
import { UpdatePoiType } from '../../models/update-poi-type';

export interface UpdatePoiType$Params {

/**
 * POI type ID
 */
  id: number;
      body: UpdatePoiType
}

export function updatePoiType(http: HttpClient, rootUrl: string, params: UpdatePoiType$Params, context?: HttpContext): Observable<StrictHttpResponse<PoiTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, updatePoiType.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PoiTypeResponse>;
    })
  );
}

updatePoiType.PATH = '/poi-types/{id}';
