/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PoiResponse } from '../../models/poi-response';
import { UpdatePoi } from '../../models/update-poi';

export interface UpdatePoi$Params {

/**
 * POI ID
 */
  id: number;
      body: UpdatePoi
}

export function updatePoi(http: HttpClient, rootUrl: string, params: UpdatePoi$Params, context?: HttpContext): Observable<StrictHttpResponse<PoiResponse>> {
  const rb = new RequestBuilder(rootUrl, updatePoi.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PoiResponse>;
    })
  );
}

updatePoi.PATH = '/pois/{id}';
